services:
  postgres:
    container_name: postgres
    image: postgres:16.3-bookworm
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5433"
    volumes:
      - ./src/main/resources/db/pg-schema.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      custom_network:
        ipv4_address: 10.5.0.3
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.8
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    networks:
      custom_network:
        ipv4_address: 10.5.0.2
    restart: always

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
